# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fleet_manager.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(539, 597)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_new_fleet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_new_fleet.setCheckable(False)
        self.pushButton_new_fleet.setAutoDefault(False)
        self.pushButton_new_fleet.setDefault(False)
        self.pushButton_new_fleet.setFlat(False)
        self.pushButton_new_fleet.setObjectName("pushButton_new_fleet")
        self.verticalLayout.addWidget(self.pushButton_new_fleet)
        self.pushButton_fleet_status = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fleet_status.setAutoDefault(False)
        self.pushButton_fleet_status.setObjectName("pushButton_fleet_status")
        self.verticalLayout.addWidget(self.pushButton_fleet_status)
        self.pushButton_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save.setShortcut("Ctrl+S")
        self.pushButton_save.setAutoDefault(False)
        self.pushButton_save.setObjectName("pushButton_save")
        self.verticalLayout.addWidget(self.pushButton_save)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_connections = QtWidgets.QComboBox(self.frame)
        self.comboBox_connections.setObjectName("comboBox_connections")
        self.horizontalLayout.addWidget(self.comboBox_connections)
        self.pushButton_refresh_ip = QtWidgets.QPushButton(self.frame)
        self.pushButton_refresh_ip.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_refresh_ip.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_refresh_ip.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pngs/refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_refresh_ip.setIcon(icon)
        self.pushButton_refresh_ip.setObjectName("pushButton_refresh_ip")
        self.horizontalLayout.addWidget(self.pushButton_refresh_ip)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_add_fleet = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_add_fleet.sizePolicy().hasHeightForWidth())
        self.pushButton_add_fleet.setSizePolicy(sizePolicy)
        self.pushButton_add_fleet.setMaximumSize(QtCore.QSize(125, 25))
        self.pushButton_add_fleet.setAutoDefault(False)
        self.pushButton_add_fleet.setObjectName("pushButton_add_fleet")
        self.horizontalLayout.addWidget(self.pushButton_add_fleet)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_fleet = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_fleet.setFont(font)
        self.label_fleet.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fleet.setObjectName("label_fleet")
        self.verticalLayout_3.addWidget(self.label_fleet)
        self.tableWidget_fleet = QtWidgets.QTableWidget(self.frame)
        self.tableWidget_fleet.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_fleet.setObjectName("tableWidget_fleet")
        self.tableWidget_fleet.setColumnCount(6)
        self.tableWidget_fleet.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fleet.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fleet.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fleet.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fleet.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fleet.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fleet.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.tableWidget_fleet)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.label_robots = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_robots.setFont(font)
        self.label_robots.setAutoFillBackground(False)
        self.label_robots.setAlignment(QtCore.Qt.AlignCenter)
        self.label_robots.setObjectName("label_robots")
        self.gridLayout.addWidget(self.label_robots, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_new_fleet.setToolTip(_translate("MainWindow", "Create new fleet"))
        self.pushButton_new_fleet.setText(_translate("MainWindow", "Create new fleet"))
        self.pushButton_fleet_status.setToolTip(_translate("MainWindow", "Fleet status"))
        self.pushButton_fleet_status.setText(_translate("MainWindow", "Fleet status"))
        self.pushButton_save.setToolTip(_translate("MainWindow", "Save"))
        self.pushButton_save.setText(_translate("MainWindow", "Save"))
        self.pushButton_refresh_ip.setToolTip(_translate("MainWindow", "Refresh IPs"))
        self.pushButton_add_fleet.setToolTip(_translate("MainWindow", "Add into fleet"))
        self.pushButton_add_fleet.setText(_translate("MainWindow", "Add"))
        self.label_fleet.setText(_translate("MainWindow", "Fleet"))
        item = self.tableWidget_fleet.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "IP Address"))
        item = self.tableWidget_fleet.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Robot"))
        item = self.tableWidget_fleet.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableWidget_fleet.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Battery"))
        item = self.tableWidget_fleet.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Position Score"))
        item = self.tableWidget_fleet.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Color"))
        self.label_robots.setText(_translate("MainWindow", "Robots"))

