TrajectoryPlannerROS:
  #Set the acceleration limits of the robot
  acc_lim_th: 0.2
  acc_lim_x: 0.2
  acc_lim_y: 0

  #Set the velocity limits of the robot
  max_vel_x: 0.2
  min_vel_x: -0.2
  max_vel_theta: 0.4
  min_vel_theta: -0.4
  max_rotational_vel: 0.4
  min_in_place_rotational_vel: 0.01
  min_in_place_vel_theta: 0.01

  #The velocity the robot will command when trying to escape from a stuck situation
  escape_vel: -0.2

  #For this example, we'll use a holonomic robot
  holonomic_robot: false

  #Set the tolerance on achieving a goal
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true

  #We'll configure how long and with what granularity we'll forward simulate trajectories
  sim_time: 1.5
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 3
  vtheta_samples: 20
  controller_frequency: 1.0
  planner_frequency: 1.0

  #Parameters for scoring trajectories
  goal_distance_bias: 0.8
  path_distance_bias: 1.0
  occdist_scale: 0.01
  heading_lookahead: 0.325

  #We'll use the Dynamic Window Approach to control instead of Trajectory Rollout for this example
  dwa: false

  #How far the robot must travel before oscillation flags are reset
  oscillation_reset_dist: 0.05

  #Eat up the plan as the robot moves along it
  prune_plan: false
