global_costmap: 
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10.0 
  publish_frequency: 10.0
  resolution: 0.05
  static_map: true
  rolling_window: false

  inflation_layer:
    inflation_radius: 0.6

  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: warehouse_layer,         type: "warehouse::WarehouseLayer"} 
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}