# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapping_tab_mw.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1308, 866)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget_main = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_main.setMovable(True)
        self.tabWidget_main.setObjectName("tabWidget_main")

        self.tab_map = QtWidgets.QWidget()
        self.tab_map.setObjectName("tab_map")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_map)
        self.gridLayout_10.setObjectName("gridLayout_10")

        self.tabWidget_map = QtWidgets.QTabWidget(self.tab_map)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_map.sizePolicy().hasHeightForWidth())
        self.tabWidget_map.setSizePolicy(sizePolicy)
        self.tabWidget_map.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget_map.setMaximumSize(QtCore.QSize(400, 16777215))
        self.tabWidget_map.setBaseSize(QtCore.QSize(0, 0))
        self.tabWidget_map.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget_map.setObjectName("tabWidget_map")

        self.tab_draw = QtWidgets.QWidget()
        self.tab_draw.setObjectName("tab_draw")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_draw)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.tab_draw)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.toolButton_select = QtWidgets.QToolButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_select.sizePolicy().hasHeightForWidth())
        self.toolButton_select.setSizePolicy(sizePolicy)
        self.toolButton_select.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pngs/mouse_click_arrow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_select.setIcon(icon)
        self.toolButton_select.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_select.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_select.setAutoRaise(True)
        self.toolButton_select.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_select.setObjectName("toolButton_select")
        self.gridLayout_2.addWidget(self.toolButton_select, 0, 0, 1, 1)

        self.toolButton_highway = QtWidgets.QToolButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_highway.sizePolicy().hasHeightForWidth())
        self.toolButton_highway.setSizePolicy(sizePolicy)
        self.toolButton_highway.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../pngs/highway.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_highway.setIcon(icon1)
        self.toolButton_highway.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_highway.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_highway.setAutoRaise(True)
        self.toolButton_highway.setObjectName("toolButton_highway")
        self.gridLayout_2.addWidget(self.toolButton_highway, 2, 1, 1, 1)

        self.toolButton_eraser = QtWidgets.QToolButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_eraser.sizePolicy().hasHeightForWidth())
        self.toolButton_eraser.setSizePolicy(sizePolicy)
        self.toolButton_eraser.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../pngs/eraser.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_eraser.setIcon(icon2)
        self.toolButton_eraser.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_eraser.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_eraser.setAutoRaise(True)
        self.toolButton_eraser.setObjectName("toolButton_eraser")
        self.gridLayout_2.addWidget(self.toolButton_eraser, 0, 1, 1, 1)

        self.toolButton_restricted_area = QtWidgets.QToolButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_restricted_area.sizePolicy().hasHeightForWidth())
        self.toolButton_restricted_area.setSizePolicy(sizePolicy)
        self.toolButton_restricted_area.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../pngs/restricted_area.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_restricted_area.setIcon(icon3)
        self.toolButton_restricted_area.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_restricted_area.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_restricted_area.setAutoRaise(True)
        self.toolButton_restricted_area.setObjectName("toolButton_restricted_area")
        self.gridLayout_2.addWidget(self.toolButton_restricted_area, 1, 1, 1, 1)

        self.toolButton_goals = QtWidgets.QToolButton(self.layoutWidget_2)
        self.toolButton_goals.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../pngs/goal.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_goals.setIcon(icon4)
        self.toolButton_goals.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_goals.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_goals.setAutoRaise(True)
        self.toolButton_goals.setObjectName("toolButton_goals")
        self.gridLayout_2.addWidget(self.toolButton_goals, 1, 0, 1, 1)
        self.toolButton_docks = QtWidgets.QToolButton(self.layoutWidget_2)
        self.toolButton_docks.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../pngs/dock.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_docks.setIcon(icon5)
        self.toolButton_docks.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_docks.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_docks.setAutoRaise(True)
        self.toolButton_docks.setObjectName("toolButton_docks")
        self.gridLayout_2.addWidget(self.toolButton_docks, 2, 0, 1, 1)

        self.verticalLayout.addWidget(self.splitter)
        self.treeWidget_objects = QtWidgets.QTreeWidget(self.tab_draw)
        self.treeWidget_objects.setAutoFillBackground(False)
        self.treeWidget_objects.setFrameShape(QtWidgets.QFrame.HLine)
        self.treeWidget_objects.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.treeWidget_objects.setLineWidth(1)
        self.treeWidget_objects.setMidLineWidth(0)
        self.treeWidget_objects.setAlternatingRowColors(True)
        self.treeWidget_objects.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.treeWidget_objects.setUniformRowHeights(False)
        self.treeWidget_objects.setAnimated(True)
        self.treeWidget_objects.setWordWrap(False)
        self.treeWidget_objects.setHeaderHidden(True)
        self.treeWidget_objects.setObjectName("treeWidget_objects")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget_objects.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget_objects.headerItem().setFont(1, font)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget_objects.headerItem().setFont(2, font)
        self.treeWidget_objects.header().setVisible(False)
        self.treeWidget_objects.header().setCascadingSectionResizes(False)
        self.treeWidget_objects.header().setHighlightSections(False)
        self.verticalLayout.addWidget(self.treeWidget_objects)

        self.tabWidget_map.addTab(self.tab_draw, "")
        self.tab_build = QtWidgets.QWidget()
        self.tab_build.setObjectName("tab_build")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_build)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.label_sources = QtWidgets.QLabel(self.tab_build)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_sources.setFont(font)
        self.label_sources.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sources.setObjectName("label_sources")
        self.verticalLayout_2.addWidget(self.label_sources)

        self.tabWidget_sources = QtWidgets.QTabWidget(self.tab_build)
        self.tabWidget_sources.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_sources.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget_sources.setObjectName("tabWidget_sources")

        self.tab_goals = QtWidgets.QWidget()
        self.tab_goals.setObjectName("tab_goals")

        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_goals)
        self.gridLayout_6.setObjectName("gridLayout_6")

        self.treeWidget_goals = QtWidgets.QTreeWidget(self.tab_goals)
        self.treeWidget_goals.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.treeWidget_goals.setLineWidth(1)
        self.treeWidget_goals.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.treeWidget_goals.setAnimated(True)
        self.treeWidget_goals.setObjectName("treeWidget_goals")
        self.gridLayout_6.addWidget(self.treeWidget_goals, 0, 0, 1, 1)

        self.tabWidget_sources.addTab(self.tab_goals, "")

        self.tab_tasks = QtWidgets.QWidget()
        self.tab_tasks.setObjectName("tab_tasks")

        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_tasks)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.listWidget_tasks = QtWidgets.QListWidget(self.tab_tasks)
        self.listWidget_tasks.setObjectName("listWidget_tasks")
        self.gridLayout_8.addWidget(self.listWidget_tasks, 0, 0, 1, 1)
        self.tabWidget_sources.addTab(self.tab_tasks, "")

        self.verticalLayout_2.addWidget(self.tabWidget_sources)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.pushButton_add_to_route = QtWidgets.QPushButton(self.tab_build)
        self.pushButton_add_to_route.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../pngs/right_arrow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_add_to_route.setIcon(icon6)
        self.pushButton_add_to_route.setObjectName("pushButton_add_to_route")
        self.horizontalLayout.addWidget(self.pushButton_add_to_route)

        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.label_routes = QtWidgets.QLabel(self.tab_build)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_routes.setFont(font)
        self.label_routes.setAlignment(QtCore.Qt.AlignCenter)
        self.label_routes.setObjectName("label_routes")
        self.verticalLayout_3.addWidget(self.label_routes)

        self.tabWidget_routes = QtWidgets.QTabWidget(self.tab_build)
        self.tabWidget_routes.setObjectName("tabWidget_routes")
        self.tab_routes = QtWidgets.QWidget()
        self.tab_routes.setObjectName("tab_routes")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_routes)
        self.gridLayout_7.setObjectName("gridLayout_7")

        self.treeWidget_routes = QtWidgets.QTreeWidget(self.tab_routes)
        self.treeWidget_routes.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.treeWidget_routes.setObjectName("treeWidget_routes")
        self.gridLayout_7.addWidget(self.treeWidget_routes, 0, 0, 1, 1)
        self.tabWidget_routes.addTab(self.tab_routes, "")
        self.verticalLayout_3.addWidget(self.tabWidget_routes)

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.pushButton_add_new_route = QtWidgets.QPushButton(self.tab_build)
        self.pushButton_add_new_route.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../pngs/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_add_new_route.setIcon(icon7)
        self.pushButton_add_new_route.setObjectName("pushButton_add_new_route")
        self.horizontalLayout_3.addWidget(self.pushButton_add_new_route)

        self.pushButton_delete_item = QtWidgets.QPushButton(self.tab_build)
        self.pushButton_delete_item.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../pngs/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete_item.setIcon(icon8)
        self.pushButton_delete_item.setObjectName("pushButton_delete_item")
        self.horizontalLayout_3.addWidget(self.pushButton_delete_item)

        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)

        self.pushButton_move_item_up = QtWidgets.QPushButton(self.tab_build)
        self.pushButton_move_item_up.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../pngs/up_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_move_item_up.setIcon(icon9)
        self.pushButton_move_item_up.setObjectName("pushButton_move_item_up")
        self.horizontalLayout_3.addWidget(self.pushButton_move_item_up)

        self.pushButton_move_item_down = QtWidgets.QPushButton(self.tab_build)
        self.pushButton_move_item_down.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../pngs/down_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_move_item_down.setIcon(icon10)
        self.pushButton_move_item_down.setObjectName("pushButton_move_item_down")
        self.horizontalLayout_3.addWidget(self.pushButton_move_item_down)










        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.tabWidget_map.addTab(self.tab_build, "")
        self.gridLayout_10.addWidget(self.tabWidget_map, 0, 0, 1, 1)

        self.frame_position_map = QtWidgets.QFrame(self.tab_map)
        self.frame_position_map.setMinimumSize(QtCore.QSize(500, 500))
        self.frame_position_map.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_position_map.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_position_map.setObjectName("frame_position_map")

        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_position_map)
        self.gridLayout_9.setObjectName("gridLayout_9")

        self.graphicsView_main_map = QtWidgets.QGraphicsView(self.frame_position_map)
        self.graphicsView_main_map.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.graphicsView_main_map.setFrameShadow(QtWidgets.QFrame.Plain)
        self.graphicsView_main_map.setLineWidth(1)
        self.graphicsView_main_map.setMidLineWidth(0)
        self.graphicsView_main_map.setObjectName("graphicsView_main_map")
        self.gridLayout_9.addWidget(self.graphicsView_main_map, 0, 1, 1, 1)
        self.gridLayout_10.addWidget(self.frame_position_map, 0, 1, 1, 1)

        self.tabWidget_main.addTab(self.tab_map, "")
        self.gridLayout.addWidget(self.tabWidget_main, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1308, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_main.setCurrentIndex(0)
        self.tabWidget_map.setCurrentIndex(1)
        self.tabWidget_sources.setCurrentIndex(0)
        self.tabWidget_routes.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton_select.setText(_translate("MainWindow", "Select"))
        self.toolButton_highway.setText(_translate("MainWindow", "       Highway        "))
        self.toolButton_eraser.setText(_translate("MainWindow", "         Eraser          "))
        self.toolButton_restricted_area.setText(_translate("MainWindow", "Restricted Area"))
        self.toolButton_goals.setText(_translate("MainWindow", "          Goals           "))
        self.toolButton_docks.setText(_translate("MainWindow", "          Docks          "))
        self.treeWidget_objects.headerItem().setText(0, _translate("MainWindow", "Object"))
        self.treeWidget_objects.headerItem().setText(1, _translate("MainWindow", "Property"))
        self.treeWidget_objects.headerItem().setText(2, _translate("MainWindow", "Value"))
        self.tabWidget_map.setTabText(self.tabWidget_map.indexOf(self.tab_draw), _translate("MainWindow", "Draw"))
        self.label_sources.setText(_translate("MainWindow", "Sources"))
        self.treeWidget_goals.headerItem().setText(0, _translate("MainWindow", "Goals"))
        self.treeWidget_goals.headerItem().setText(1, _translate("MainWindow", "ObjNm"))
        self.tabWidget_sources.setTabText(self.tabWidget_sources.indexOf(self.tab_goals), _translate("MainWindow", "Goals"))
        self.tabWidget_sources.setTabText(self.tabWidget_sources.indexOf(self.tab_tasks), _translate("MainWindow", "Tasks"))
        self.label_routes.setText(_translate("MainWindow", "Routes"))
        self.treeWidget_routes.headerItem().setText(0, _translate("MainWindow", "Routes"))
        self.treeWidget_routes.headerItem().setText(1, _translate("MainWindow", "ObjNm"))
        self.tabWidget_routes.setTabText(self.tabWidget_routes.indexOf(self.tab_routes), _translate("MainWindow", "Routes"))
        self.pushButton_add_new_route.setToolTip(_translate("MainWindow", "Add new route"))
        self.pushButton_delete_item.setToolTip(_translate("MainWindow", "Delete"))
        self.pushButton_move_item_up.setToolTip(_translate("MainWindow", "Move item up"))
        self.pushButton_move_item_down.setToolTip(_translate("MainWindow", "Move item down"))
        self.tabWidget_map.setTabText(self.tabWidget_map.indexOf(self.tab_build), _translate("MainWindow", "Build"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_map), _translate("MainWindow", "Map"))

