# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rt_plot.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1968, 1128)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
    
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(1530, 40, 151, 145))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_add_point = QtWidgets.QPushButton(self.frame)
        self.pushButton_add_point.setGeometry(QtCore.QRect(50, 110, 81, 25))
        self.pushButton_add_point.setObjectName("pushButton_add_point")
        self.lineEdit_y = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_y.setGeometry(QtCore.QRect(60, 40, 81, 25))
        self.lineEdit_y.setObjectName("lineEdit_y")
        self.lineEdit_x = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_x.setGeometry(QtCore.QRect(60, 10, 81, 25))
        self.lineEdit_x.setObjectName("lineEdit_x")
        self.label_x = QtWidgets.QLabel(self.frame)
        self.label_x.setGeometry(QtCore.QRect(10, 10, 40, 21))
        self.label_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_x.setObjectName("label_x")
        self.label_y = QtWidgets.QLabel(self.frame)
        self.label_y.setGeometry(QtCore.QRect(10, 40, 40, 21))
        self.label_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_y.setObjectName("label_y")
        self.label_yaw = QtWidgets.QLabel(self.frame)
        self.label_yaw.setGeometry(QtCore.QRect(10, 70, 40, 21))
        self.label_yaw.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_yaw.setObjectName("label_yaw")
        self.lineEdit_yaw = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_yaw.setGeometry(QtCore.QRect(60, 70, 81, 25))
        self.lineEdit_yaw.setObjectName("lineEdit_yaw")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(1530, 200, 421, 311))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.tableWidget_state_list = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget_state_list.setGeometry(QtCore.QRect(10, 10, 402, 192))
        self.tableWidget_state_list.setObjectName("tableWidget_state_list")
        self.tableWidget_state_list.setColumnCount(4)
        self.tableWidget_state_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_state_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_state_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_state_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_state_list.setHorizontalHeaderItem(3, item)
        self.pushButton_publish_states = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_publish_states.setGeometry(QtCore.QRect(320, 210, 89, 25))
        self.pushButton_publish_states.setObjectName("pushButton_publish_states")
        self.pushButton_remove_point = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_remove_point.setEnabled(False)
        self.pushButton_remove_point.setGeometry(QtCore.QRect(10, 210, 89, 25))
        self.pushButton_remove_point.setObjectName("pushButton_remove_point")
        self.pushButton_up_point = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_up_point.setEnabled(False)
        self.pushButton_up_point.setGeometry(QtCore.QRect(10, 240, 89, 25))
        self.pushButton_up_point.setObjectName("pushButton_up_point")
        self.pushButton_down_point = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_down_point.setEnabled(False)
        self.pushButton_down_point.setGeometry(QtCore.QRect(10, 270, 89, 25))
        self.pushButton_down_point.setObjectName("pushButton_down_point")
        self.pushButton_manual_drive = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_manual_drive.setGeometry(QtCore.QRect(1530, 520, 111, 25))
        self.pushButton_manual_drive.setObjectName("pushButton_manual_drive")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(10, 10, 1491, 981))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setMinimumSize(QtCore.QSize(1491, 981))
        self.splitter_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_draw = QtWidgets.QWidget()
        self.tab_draw.setObjectName("tab_draw")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_draw)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.tab_draw)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.toolButton_select = QtWidgets.QToolButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_select.sizePolicy().hasHeightForWidth())
        self.toolButton_select.setSizePolicy(sizePolicy)
        self.toolButton_select.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pngs/mouse_click_arrow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_select.setIcon(icon)
        self.toolButton_select.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_select.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_select.setAutoRaise(True)
        self.toolButton_select.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_select.setObjectName("toolButton_select")
        self.gridLayout_2.addWidget(self.toolButton_select, 0, 0, 1, 1)

        self.toolButton_goals = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_goals.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../pngs/goal.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_goals.setIcon(icon1)
        self.toolButton_goals.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_goals.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_goals.setAutoRaise(True)
        self.toolButton_goals.setObjectName("toolButton_goals")
        self.gridLayout_2.addWidget(self.toolButton_goals, 1, 0, 1, 1)

        self.toolButton_highway = QtWidgets.QToolButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_highway.sizePolicy().hasHeightForWidth())
        self.toolButton_highway.setSizePolicy(sizePolicy)
        self.toolButton_highway.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../pngs/highway.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_highway.setIcon(icon3)
        self.toolButton_highway.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_highway.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_highway.setAutoRaise(True)
        self.toolButton_highway.setObjectName("toolButton_highway")
        self.gridLayout_2.addWidget(self.toolButton_highway, 2, 1, 1, 1)

        self.toolButton_restricted_area = QtWidgets.QToolButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_restricted_area.sizePolicy().hasHeightForWidth())
        self.toolButton_restricted_area.setSizePolicy(sizePolicy)
        self.toolButton_restricted_area.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../pngs/restricted_area.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_restricted_area.setIcon(icon4)
        self.toolButton_restricted_area.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_restricted_area.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_restricted_area.setAutoRaise(True)
        self.toolButton_restricted_area.setObjectName("toolButton_restricted_area")
        self.gridLayout_2.addWidget(self.toolButton_restricted_area, 1, 1, 1, 1)

        self.toolButton_eraser = QtWidgets.QToolButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_eraser.sizePolicy().hasHeightForWidth())
        self.toolButton_eraser.setSizePolicy(sizePolicy)
        self.toolButton_eraser.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../pngs/eraser.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_eraser.setIcon(icon5)
        self.toolButton_eraser.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_eraser.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_eraser.setAutoRaise(True)
        self.toolButton_eraser.setObjectName("toolButton_eraser")
        self.gridLayout_2.addWidget(self.toolButton_eraser, 0, 1, 1, 1)

        self.tableWidget = QtWidgets.QTableWidget(self.splitter)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 80))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 700))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab_draw, "")
        self.tab_build = QtWidgets.QWidget()
        self.tab_build.setObjectName("tab_build")
        self.tabWidget.addTab(self.tab_build, "")
        self.frame_position = QtWidgets.QFrame(self.splitter_2)
        self.frame_position.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_position.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_position.setObjectName("frame_position")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_position)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_position_monitoring = QtWidgets.QWidget(self.frame_position)
        self.widget_position_monitoring.setObjectName("widget_position_monitoring")
        self.gridLayout_3.addWidget(self.widget_position_monitoring, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1968, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuMap = QtWidgets.QMenu(self.menubar)
        self.menuMap.setObjectName("menuMap")
        self.menuRobot = QtWidgets.QMenu(self.menubar)
        self.menuRobot.setObjectName("menuRobot")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setOrientation(QtCore.Qt.Horizontal)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../pngs/connection.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnect.setIcon(icon6)
        self.actionConnect.setObjectName("actionConnect")
        self.actionUpload_Map = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../pngs/upload_map.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpload_Map.setIcon(icon7)
        self.actionUpload_Map.setObjectName("actionUpload_Map")
        self.actionStop = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../pngs/stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon8)
        self.actionStop.setObjectName("actionStop")
        self.actionDrive = QtWidgets.QAction(MainWindow)
        self.actionDrive.setObjectName("actionDrive")
        self.actionMap_Creation = QtWidgets.QAction(MainWindow)
        self.actionMap_Creation.setObjectName("actionMap_Creation")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../pngs/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon9)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionOpen_file)
        self.menuRobot.addAction(self.actionStop)
        self.menuRobot.addAction(self.actionDrive)
        self.menuRobot.addAction(self.actionMap_Creation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuRobot.menuAction())
        self.menubar.addAction(self.menuMap.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionConnect)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUpload_Map)
        self.toolBar.addAction(self.actionSave)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_add_point.setText(_translate("MainWindow", "Add point"))
        self.label_x.setText(_translate("MainWindow", "X :"))
        self.label_y.setText(_translate("MainWindow", "Y :"))
        self.label_yaw.setText(_translate("MainWindow", "Yaw :"))
        item = self.tableWidget_state_list.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "State"))
        item = self.tableWidget_state_list.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "x"))
        item = self.tableWidget_state_list.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "y"))
        item = self.tableWidget_state_list.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "yaw"))
        self.pushButton_publish_states.setText(_translate("MainWindow", "Publish"))
        self.pushButton_remove_point.setText(_translate("MainWindow", "Remove"))
        self.pushButton_up_point.setText(_translate("MainWindow", "Up"))
        self.pushButton_down_point.setText(_translate("MainWindow", "Down"))
        self.pushButton_manual_drive.setText(_translate("MainWindow", "Manual Drive"))
        self.toolButton_select.setText(_translate("MainWindow", "Select"))
        self.toolButton_goals.setText(_translate("MainWindow", "          Goals           "))
        self.toolButton_docks.setText(_translate("MainWindow", "          Docks          "))
        self.toolButton_highway.setText(_translate("MainWindow", "       Highway        "))
        self.toolButton_restricted_area.setText(_translate("MainWindow", "Restricted Area"))
        self.toolButton_eraser.setText(_translate("MainWindow", "         Eraser          "))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "X"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Y"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Yaw"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_draw), _translate("MainWindow", "Draw"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_build), _translate("MainWindow", "Build"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuMap.setTitle(_translate("MainWindow", "Map"))
        self.menuRobot.setTitle(_translate("MainWindow", "Robot"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.actionOpen_file.setText(_translate("MainWindow", "Open file"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionConnect.setToolTip(_translate("MainWindow", "Connect"))
        self.actionUpload_Map.setText(_translate("MainWindow", "Upload Map"))
        self.actionUpload_Map.setToolTip(_translate("MainWindow", "Upload Map"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionDrive.setText(_translate("MainWindow", "Drive"))
        self.actionMap_Creation.setText(_translate("MainWindow", "Map Creation"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setToolTip(_translate("MainWindow", "Save"))

